/*
DISCLAIMER: This source code was generated by Dapp, and is supplied to you by
kerofrog.

kerofrog grants you a personal, non-exclusive license to use, reproduce, modify
and redistribute this source code, with or without modifications in source
and/or binary forms.  However, if you redistribute the source code in its entirety
and without modifications, you must retain this notice and the following text and
disclaimers in all such redistributions.

The source code is provided by kerofrog on an "AS IS" basis.  kerofrog makes no
warranties, express or implied, including without limitation the implied warranties
of non-infringement, merchantability and fitness for a particular purpose, regarding
the source code or its use and operation alone or in combination with your products.

In no event shall kerofrog be liable for any special, indirect, incidental or
consequential damages (including, but not limited to, loss of use, data, or profits;
or business interruption) arising in any way out of the use, reproduction,
modification and/or distribution of the source code.

Copyright (C) 2010 kerofrog. All Rights Reserved.
*/

// Header File
#import "Homescreen_ActivationViewController.h"

@interface Homescreen_ActivationViewController ()

- (IBAction)btnButton1Tapped:(id)sender;

@end

@implementation Homescreen_ActivationViewController

#pragma mark -
#pragma mark Initialisation

- (id)initWithCoder:(NSCoder *)aDecoder {
	self = [super initWithCoder:aDecoder];
	if (self) {
		// Set the title for this view controller
		// Note: In future we will copy over the title from any created UINavigationBar objects
		self.title = @"Homescreen Activation";

		[[UIApplication sharedApplication] setStatusBarHidden:NO withAnimation:UIStatusBarAnimationNone];
	}
	return self;
}

#pragma mark -
#pragma mark UIViewController Delegates

- (void)didReceiveMemoryWarning {
	[super didReceiveMemoryWarning];
	// Dispose of any resources that can be recreated.
}

- (void)viewDidUnload {
	[super viewDidUnload];
}

-(void)viewWillAppear:(BOOL)animated {
	[super viewWillAppear:animated];

	[self.navigationController setNavigationBarHidden:YES animated:NO];
	// Update support iOS 7
	if ([self respondsToSelector:@selector(edgesForExtendedLayout)]) {
		self.edgesForExtendedLayout = UIRectEdgeNone;
		self.navigationController.navigationBar.translucent = NO;
	}
}

-(void)viewWillDisappear:(BOOL)animated {
	[super viewWillDisappear:animated];

	// Revert to default settings
	if ([self respondsToSelector:@selector(edgesForExtendedLayout)]) {
		self.edgesForExtendedLayout = UIRectEdgeAll;
	}
}

- (void)viewDidLoad 
{
	[super viewDidLoad];
	// Do any additional setup after loading the view, typically from a nib.
	// Load webview methods
	[self loadWebView1WithURLString:@"https://dl.dropboxusercontent.com/s/0nz6zc77q89mc0x/mockup_hs_ios_704.htm"];
}

#pragma mark - === WebView methods ===
- (void)loadWebView1WithURLString:(NSString *) urlString {
	NSURL *webURL = [NSURL URLWithString:urlString];
	NSURLRequest *webURLRequest = [NSURLRequest requestWithURL:webURL];
	[_webView1 loadRequest:webURLRequest];
}

#pragma mark - === Button methods ===
- (IBAction)btnButton1Tapped:(id)sender {
}


@end

